apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  version: 1.0.0
  description: A Helm chart for my application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
      - name: my-application
        image: my-application:latest
        ports:
        - containerPort: 80